[package]
name = "cycler-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "cycler-ui"
path = "src/main.rs"

[dependencies]
cycler-core.workspace = true
anyhow.workspace = true
eframe = "0.35"
egui = "0.35"
egui_bench = { git = "https://github.com/v0l/egui_bench", rev = "768cd8292e3886d4a9ff399c38dd28835437d3f0" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
signal-hook = "0.4.4"
